import Footer from "@/component/Footer/Footer";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import ContextProvider from "@/contexts/provider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Navbar />
      <body>
        <ContextProvider>
          {children}
          <ToastContainer />
        </ContextProvider>
      </body>
      <Footer />
    </html>
  );
}
